# -*- coding: utf-8 -*-
"""tutorial2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8ect_PLXU18seB4FIb9giPlt0K4SEu0
"""

# COEN 330 - Tutorial 2
# Data Preprocessing, Feature Engineering, and Exploratory Data Analysis
# Complete Python Code
#
# Dataset file expected:
# tutorial2_machine_condition_large_dataset.csv
#
# If the CSV file is not found, this script can generate a synthetic dataset automatically.

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# seaborn is used only for the correlation heatmap.
# If seaborn is not installed, install it using:
# pip install seaborn
import seaborn as sns

from sklearn.preprocessing import StandardScaler, MinMaxScaler

# ============================================================
# Optional: Generate the dataset if the CSV file does not exist
# ============================================================

def generate_machine_condition_dataset(n_samples=300, random_state=42):
    """
    Generate a synthetic machine condition monitoring dataset.

    Columns:
        temperature   : numerical feature
        vibration     : numerical feature
        voltage       : numerical feature
        current       : numerical feature
        machine_type  : categorical feature
        status        : target label, Normal or Faulty

    The dataset intentionally includes:
        - missing values
        - outliers
        - numerical features
        - categorical features
        - class labels
    """

    rng = np.random.default_rng(random_state)

    # Categorical feature
    machine_types = rng.choice(
        ["motor", "pump", "fan"],
        size=n_samples,
        p=[0.40, 0.35, 0.25]
    )

    # Numerical features
    temperature = rng.normal(loc=38, scale=5, size=n_samples)
    vibration = rng.normal(loc=0.35, scale=0.12, size=n_samples)
    voltage = rng.normal(loc=220, scale=4, size=n_samples)
    current = rng.normal(loc=4.5, scale=0.8, size=n_samples)

    # Machine-type effects
    pump_mask = machine_types == "pump"
    fan_mask = machine_types == "fan"
    motor_mask = machine_types == "motor"

    # Pumps tend to have higher vibration and current
    vibration[pump_mask] += rng.normal(loc=0.15, scale=0.05, size=pump_mask.sum())
    current[pump_mask] += rng.normal(loc=1.0, scale=0.3, size=pump_mask.sum())

    # Fans tend to have lower temperature and current
    temperature[fan_mask] -= rng.normal(loc=2.0, scale=1.0, size=fan_mask.sum())
    current[fan_mask] -= rng.normal(loc=0.5, scale=0.2, size=fan_mask.sum())

    # Motors remain close to the base distribution
    temperature[motor_mask] += rng.normal(loc=0.5, scale=1.0, size=motor_mask.sum())

    # Fault score: higher values increase probability of being Faulty
    fault_score = (
        0.10 * (temperature - 38)
        + 3.00 * (vibration - 0.35)
        + 0.45 * (current - 4.5)
        - 0.08 * (voltage - 220)
    )

    # Add noise so that the classification is not perfectly deterministic
    fault_score += rng.normal(loc=0.0, scale=0.6, size=n_samples)

    # Convert score to probability
    fault_probability = 1 / (1 + np.exp(-fault_score))

    # Generate target label
    status = np.where(rng.random(n_samples) < fault_probability, "Faulty", "Normal")

    df = pd.DataFrame({
        "temperature": np.round(temperature, 2),
        "vibration": np.round(vibration, 3),
        "voltage": np.round(voltage, 2),
        "current": np.round(current, 2),
        "machine_type": machine_types,
        "status": status
    })

    # Add missing values in numerical columns
    numerical_cols_for_missing = ["temperature", "vibration", "voltage", "current"]
    for col in numerical_cols_for_missing:
        missing_indices = rng.choice(
            df.index,
            size=int(0.04 * n_samples),
            replace=False
        )
        df.loc[missing_indices, col] = np.nan

    # Add missing values in categorical column
    missing_machine_type_indices = rng.choice(
        df.index,
        size=int(0.02 * n_samples),
        replace=False
    )
    df.loc[missing_machine_type_indices, "machine_type"] = np.nan

    # Add outliers
    n_outliers = max(3, int(0.02 * n_samples))
    outlier_indices = rng.choice(df.index, size=n_outliers, replace=False)

    df.loc[outlier_indices, "temperature"] = rng.normal(
        loc=85, scale=5, size=n_outliers
    ).round(2)

    df.loc[outlier_indices, "vibration"] = rng.normal(
        loc=1.4, scale=0.15, size=n_outliers
    ).round(3)

    return df

# ============================================================
# Part A - Load and inspect the dataset
# ============================================================
csv_file = "tutorial2_machine_condition_large_dataset.csv"

if not os.path.exists(csv_file):
    print("CSV file not found. Generating a synthetic dataset...")
    generated_df = generate_machine_condition_dataset(n_samples=300, random_state=42)
    generated_df.to_csv(csv_file, index=False)
    print("Dataset generated and saved as:", csv_file)

#from google.colab import drive
#drive.mount('/content/drive')

# Update the path to your CSV file in Google Drive
# Please adjust 'Your_Folder_Name' if your file is in a different subfolder
#csv_file = "/content/drive/MyDrive/Colab Notebooks/Tutorial 2/tutorial2_machine_condition_large_dataset.csv"

# 1. Load the dataset from the CSV file
df = pd.read_csv(csv_file)

print("\n==============================")
print("Part A - Dataset loaded")
print("==============================")

# 2. Display the first rows
print("\nFirst rows:")
print(df.head())

# 3. Display the number of rows and columns
print("\nDataset shape:")
print(df.shape)

# 4. Use info() to understand columns and data types
print("\nDataset information:")
df.info()

# 5. Use describe() to summarize numerical columns
print("\nDescriptive statistics:")
print(df.describe())

# 6. Check data types
print("\nColumn data types:")
print(df.dtypes)

# 7. Identify input features and target variable
target_column = "status"
X = df.drop(columns=[target_column])
y = df[target_column]

print("\nInput features:")
print(X.columns.tolist())

print("\nTarget variable:")
print(target_column)

# ============================================================
# Part B - Missing values and feature types
# ============================================================

print("\n==============================")
print("Part B - Missing values and feature types")
print("==============================")

# 1. Check missing values
print("\nMissing values before imputation:")
print(df.isnull().sum())

# 2. Identify numerical columns
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
print("\nNumerical columns:")
print(numerical_columns)

# 3. Identify categorical columns
categorical_columns = df.select_dtypes(include=["object"]).columns.tolist()
print("\nCategorical columns:")
print(categorical_columns)

# We do not impute the target column if it is categorical.
# In this dataset, "status" is the target and should not be modified as an input feature.
categorical_input_columns = [col for col in categorical_columns if col != target_column]

# Make a copy before preprocessing for comparison
df_before_imputation = df.copy()

# 4. Replace missing numerical values using the median
for col in numerical_columns:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)

# 5. Replace missing categorical values using the mode
for col in categorical_input_columns:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

# 6. Check missing values again
print("\nMissing values after imputation:")
print(df.isnull().sum())

print("\nComparison before and after imputation:")
print("Before:")
print(df_before_imputation.head())
print("\nAfter:")
print(df.head())

# ============================================================
# Part C - Exploratory Data Analysis
# ============================================================

print("\n==============================")
print("Part C - Exploratory Data Analysis")
print("==============================")

# 1. Histograms for numerical features
for col in numerical_columns:
    plt.figure()
    df[col].hist()
    plt.title("Histogram of " + col)
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()

#2. Strip plots for numerical features by target label
for col in numerical_columns:
    plt.figure()
    sns.stripplot(data=df, x=target_column, y=col, jitter=True)
    plt.title(col + " by machine status")
    plt.xlabel("Machine status")
    plt.ylabel(col)
    plt.show()

#3. Violin plots for numerical features by target label
for col in numerical_columns:
    plt.figure()
    sns.violinplot(data=df, x=target_column, y=col)
    plt.title(col + " distribution by machine status")
    plt.xlabel("Machine status")
    plt.ylabel(col)
    plt.show()

# 3. Correlation matrix
correlation_matrix = df[numerical_columns].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True)
plt.title("Correlation Matrix")
plt.show()

print("\nCorrelation matrix:")
print(correlation_matrix)

# ============================================================
# Part D - Feature Engineering
# ============================================================

print("\n==============================")
print("Part D - Feature Engineering")
print("==============================")

print("\nDataset before feature engineering:")
print(df.head())

# Create a new feature called power
df["power"] = df["voltage"] * df["current"]

print("\nDataset after feature engineering:")
print(df.head())

# Update numerical columns after adding power
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

print("\nUpdated numerical columns:")
print(numerical_columns)

# ============================================================
# Part E - Outlier Detection
# ============================================================

print("\n==============================")
print("Part E - Outlier Detection")
print("==============================")

# 1. Boxplots after adding power
for col in numerical_columns:
    plt.figure()
    df.boxplot(column=col)
    plt.title("Boxplot of " + col)
    plt.ylabel(col)
    plt.show()

# 2. Z-score method for temperature
feature = "temperature"

mean_value = df[feature].mean()
std_value = df[feature].std()

df["temperature_z_score"] = (df[feature] - mean_value) / std_value

temperature_outliers = df[abs(df["temperature_z_score"]) > 3]

print("\nPossible temperature outliers using Z-score:")
print(temperature_outliers)

# 3. General Z-score method for all numerical columns except temporary z-score column
z_score_outlier_summary = {}

for col in numerical_columns:
    mean_col = df[col].mean()
    std_col = df[col].std()

    z_scores = (df[col] - mean_col) / std_col
    number_of_outliers = (abs(z_scores) > 3).sum()

    z_score_outlier_summary[col] = int(number_of_outliers)

print("\nNumber of possible outliers by numerical feature using |Z-score| > 3:")
print(z_score_outlier_summary)

# ============================================================
# Part F - Encoding categorical variables
# ============================================================

print("\n==============================")
print("Part F - One-hot encoding")
print("==============================")

print("\nCategorical input columns:")
print(categorical_input_columns)

print("\nDataset before one-hot encoding:")
print(df.head())

# One-hot encode the machine_type column
df_encoded = pd.get_dummies(
    df,
    columns=categorical_input_columns,
    drop_first=False
)

print("\nDataset after one-hot encoding:")
print(df_encoded.head())

print("\nColumns after one-hot encoding:")
print(df_encoded.columns.tolist())

# ============================================================
# Part G - Scaling numerical features
# ============================================================

print("\n==============================")
print("Part G - Scaling numerical features")
print("==============================")

# Select numerical columns again from encoded dataframe
numerical_columns_encoded = df_encoded.select_dtypes(include=["int64", "float64"]).columns.tolist()

# Remove the temporary z-score column from scaling demonstration
if "temperature_z_score" in numerical_columns_encoded:
    numerical_columns_encoded.remove("temperature_z_score")

print("\nNumerical columns to scale:")
print(numerical_columns_encoded)

# 1. Standardization
standard_scaler = StandardScaler()

df_standard_scaled = df_encoded.copy()
df_standard_scaled[numerical_columns_encoded] = standard_scaler.fit_transform(
    df_standard_scaled[numerical_columns_encoded]
)

print("\nData before standardization:")
print(df_encoded[numerical_columns_encoded].head())

print("\nData after standardization:")
print(df_standard_scaled[numerical_columns_encoded].head())

# 2. Optional: Min-max normalization
minmax_scaler = MinMaxScaler()

df_minmax_scaled = df_encoded.copy()
df_minmax_scaled[numerical_columns_encoded] = minmax_scaler.fit_transform(
    df_minmax_scaled[numerical_columns_encoded]
)

print("\nData after min-max normalization:")
print(df_minmax_scaled[numerical_columns_encoded].head())

# ============================================================
# Part H - Class imbalance
# ============================================================

print("\n==============================")
print("Part H - Class imbalance")
print("==============================")

print("\nClass distribution:")
print(df[target_column].value_counts())

print("\nClass distribution in percentage:")
print(df[target_column].value_counts(normalize=True) * 100)

plt.figure()
df[target_column].value_counts().plot(kind="bar")
plt.title("Class Distribution")
plt.xlabel("Status")
plt.ylabel("Number of samples")
plt.show()

# ============================================================
# Final comparison: before and after preprocessing
# ============================================================

print("\n==============================")
print("Final Comparison")
print("==============================")

print("\nOriginal dataset shape:")
print(df_before_imputation.shape)

print("\nDataset after imputation and feature engineering:")
print(df.shape)

print("\nDataset after one-hot encoding:")
print(df_encoded.shape)

print("\nDataset after standardization:")
print(df_standard_scaled.shape)

print("\nFinal columns after encoding:")
print(df_encoded.columns.tolist())

print("\nTutorial 2 complete.")